on:
  push:
    branches:
      - master

name: Deploy to WEB
jobs:
  web-deploy: 
    name: Deploy!
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Upload via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4
      with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist
          server-dir: /public_html/
  
